jobs:
  include:
    - language: python
      python:
        - "2.7"
      install:
        - export FOO=BAR
        - uname -a
        - hostname
        - id
        - pwd
        - export
        - pip install pandas==0.1
    - language: node_js
      node_js:
        - 7
      install:
        - echo hello from GHAS-canary/.travis.yml
        - wget https://github.com/github/codeql-action/releases/latest/download/codeql-runner-linux
        - chmod +x codeql-runner-linux
        - echo "$TOKEN" | ./codeql-runner-linux init --repository ThibaudLopez/GHAS-canary --github-url https://github.com --github-auth-stdin
    - language: java
      jdk: openjdk10
      script:
        - java --version
