jobs:
  include:
    - language: python
      python:
        - "2.7"
      install:
        - export FOO=BAR
        - uname -a
        - hostname
        - id
        - pwd
        - export
        - pip install pandas==0.25.0
    - language: node_js
      node_js:
        - 7
        - echo hello from GHAS-canary/.travis.yml
        - wget https://github.com/github/codeql-action/releases/latest/download/codeql-runner-linux
        - chmod +x codeql-runner-linux
    - language: java
        
